version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  mocks3:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minio-user
      MINIO_ROOT_PASSWORD: minio1234
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - mocks3-data:/data

  uploader-service:
    build: ./uploader-service
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
      - mocks3

  processor-service:
    build: ./processor-service
    depends_on:
      - rabbitmq
      - mocks3

volumes:
  mocks3-data:
